version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "@docusaurus/*"
    open-pull-requests-limit: 0 # keep only security updates and disable version updates
