project_name: fasttrackml
builds:
  - binary: fml
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm64
      - amd64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X 'github.com/G-Research/fasttrackml/pkg/version.Version={{.Version}}'
      - >-
        {{- if eq .Os "linux" }}
        -linkmode external -extldflags -static
        {{- end }}
    flags:
      - -tags
      - netgo,osusergo,sqlite_foreign_keys,sqlite_math_functions,sqlite_omit_load_extension,sqlite_unlock_notify,sqlite_vacuum_incr
    hooks:
      pre:
        # fix wrong path in libm.a on linux/arm64 cross-compiler for linux/amd64
        - >-
          {{- if and (eq .Os "linux") (eq .Arch "amd64") (eq .Runtime.Goos "linux") (eq .Runtime.Goarch "arm64") }}
          sh -c "sed -i -e 's,lib/x86_64-linux-gnu,x86_64-linux-gnu/lib,g' /usr/x86_64-linux-gnu/lib/libm.a"
          {{- else }}true{{ end }}
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
          {{- if eq .Arch "arm64"}}CC=oa64-clang{{- end }}
        {{- end }}
        {{- if eq .Os "linux" }}
          {{- if eq .Arch "amd64"}}CC=x86_64-linux-gnu-gcc{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-linux-gnu-gcc{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
        {{- end }}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: checksums.txt
  algorithm: sha256
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
