services:
  service:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      FML_DATABASE_URI: postgres://postgres:postgres@postgres/postgres
      FML_LOG_LEVEL: debug

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres

  integration-tests:
    image: golang:1.20
    command: make test-go-integration
    volumes:
      - .:/go/src
      - go-cache:/go/pkg
    working_dir: /go/src
    depends_on:
      - service
      - postgres
    environment:
      FML_DATABASE_URI: postgres://postgres:postgres@postgres/postgres
      FML_SERVICE_URI: http://service:5000

volumes:
  go-cache: