[tool.poetry]
name = "fast-track-test"
version = "0.1.0"
description = "A Stable Baselines Example for Fast Track"
authors = ["Sharpz7 <adam.mcarthur62@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
mlflow = "^2.9.1"
torch = "^2.1.1"
stable-baselines3 = "^2.2.1"
tqdm = "^4.66.1"
moviepy = "^1.0.3"
gymnasium = {extras = ["classic-control"], version = "^0.29.1"}
pynvml = "^11.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
