name: Feature request
description: Suggest a new idea for FastTrackML
title: "[FEATURE REQUEST]: <title>"
labels: [ "feature" ]

body:
  - type: textarea
    id: related-problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: ex. I'm always frustrated when [...]
    validations:
      required: false

  - type: textarea
    id: describe-solution-or-desired-feature
    attributes:
      label: Describe the solution/feature you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: ex. I wish I could [...]
    validations:
      required: true

  - type: textarea
    id: describe-alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
