version: "3.9"
services:
  fasttrack-service:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    depends_on:
      - fasttrack-minio
      - fasttrack-postgres
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: "YFptmVrlVdOgnHZ8Idse"
      AWS_SECRET_ACCESS_KEY: "ZeKsyUJikIAJQVtYsQNtdXx8qv9eevL94qFOx0Jh"
    networks:
      - fasttrack-network

  fasttrack-postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fasttrack-network

  fasttrack-integration-tests:
    build:
      context: ../
      dockerfile: docker/tests/integration/Dockerfile
    external_links:
      - fasttrack-service:fasttrack-service
    environment:
      AWS_ACCESS_KEY_ID: "YFptmVrlVdOgnHZ8Idse"
      AWS_SECRET_ACCESS_KEY: "ZeKsyUJikIAJQVtYsQNtdXx8qv9eevL94qFOx0Jh"
      S3_BASE_URL: http://fasttrack-minio:9000
      DATABASE_DSN: postgres://postgres:postgres@fasttrack-postgres:5432/postgres
      SERVICE_BASE_URL: http://fasttrack-service:8080
    networks:
      - fasttrack-network

  fasttrack-minio:
    image: minio/minio:latest
    entrypoint: sh
    command: -c 'mkdir -p /data/fasttrackml && minio server /data'
    environment:
      MINIO_ROOT_USER: "YFptmVrlVdOgnHZ8Idse"
      MINIO_ROOT_PASSWORD: "ZeKsyUJikIAJQVtYsQNtdXx8qv9eevL94qFOx0Jh"
      MINIO_ADDRESS: ":9000"
      MINIO_CONSOLE_ADDRESS: ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - fasttrack-network

networks:
  fasttrack-network:
