version: "3.9"
services:
  fasttrack-service:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    depends_on:
      - fasttrack-postgres
      - fasttrack-localstack
    ports:
      - "8080:8080"
    environment:
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "key"
      AWS_SECRET_ACCESS_KEY: "secret"
    networks:
      - fasttrack-network

  fasttrack-postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fasttrack-network

  fasttrack-integration-tests:
    build:
      context: ../
      dockerfile: docker/tests/integration/Dockerfile
    external_links:
      - fasttrack-service:fasttrack-service
    environment:
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "key"
      AWS_SECRET_ACCESS_KEY: "secret"
      S3_BASE_URL: http://fasttrack-localstack:4566
      DATABASE_DSN: postgres://postgres:postgres@fasttrack-postgres:5432/postgres
      SERVICE_BASE_URL: http://fasttrack-service:8080
    networks:
      - fasttrack-network

  fasttrack-localstack:
    build:
      context: ../
      dockerfile: docker/tests/localstack/Dockerfile
    ports:
      - "4566:4566"
    networks:
      - fasttrack-network
    environment:
      - DEBUG=1
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1

networks:
  fasttrack-network:
