version: "3.9"
services:
  fasttrack-service:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    depends_on:
      - fasttrack-postgres
    ports:
      - "8080:8080"
    networks:
      - fasttrack-network

  fasttrack-postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fasttrack-network

  fasttrack-integration-tests:
    build:
      context: ../
      dockerfile: docker/tests/integration/Dockerfile
    external_links:
      - fasttrack-service:fasttrack-service
    environment:
      DATABASE_DSN: postgres://postgres:postgres@fasttrack-postgres:5432/postgres
      SERVICE_BASE_URL: http://fasttrack-service:8080
    networks:
      - fasttrack-network

networks:
  fasttrack-network:
