version: '3'
services:
    mlflowdb:
      image: postgres:13
      container_name: mlflowdb
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=mlflow_db
      networks:
        - mlflow_network
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 5s
        timeout: 5s

    fasttrackdb:
      image: postgres:13
      container_name: fasttrackdb
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=fasttrack_db
      networks:
        - fasttrack_network
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 5s
        timeout: 5s

    mlflowpostgres:
      image: seeloz/mlflow-server
      ports:
        - 6000:5000
      environment:
        - BACKEND_URI=postgresql://postgres:postgres@mlflowdb:5432/mlflow_db
      depends_on:
        mlflowdb:
          condition: service_healthy
      networks:
        - mlflow_network
    
    mlflow:
      image: seeloz/mlflow-server
      ports:
        - 6001:5000
      networks:
        - mlflow_network

    fasttrack:
      image: gresearch/fasttrackml
      networks:
        - fasttrack_network
      ports:
        - 6002:5000
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
        interval: 2s
        timeout: 5s
        start_period: 5m

    fasttrackpostgres:
      image: gresearch/fasttrackml
      networks:
        - fasttrack_network
      ports:
        - 6003:5000
      environment:
        - FML_DATABASE_URI=postgresql://postgres:postgres@fasttrackdb:5432/fasttrack_db
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
        interval: 5s
        timeout: 10s
        retries: 3
      depends_on:
        fasttrackdb:
          condition: service_healthy

    logging_test_mlflow_sqlite:
      image: grafana/k6:latest
      command: run  -u 20 -i 100  k6LoggingPerfScript.js --out csv=benchmark_outputs/mlflowsqlitelogging.csv -e HOSTNAME=mlflow:5000 
      working_dir: /src
      volumes:
        - .:/src
      networks:
        - mlflow_network
      depends_on:
        - mlflow
      
    logging_test_mlflow_postgres:
      image: grafana/k6:latest
      command: run  -u 20 -i 100  k6LoggingPerfScript.js --out csv=benchmark_outputs/mlflowpostgreslogging.csv -e HOSTNAME=mlflowpostgres:5000 
      working_dir: /src
      volumes:
        - .:/src
      networks:
        - mlflow_network
      depends_on:
        - mlflowpostgres

    logging_test_fasttrack_sqlite:
      image: grafana/k6:latest
      command: run  -u 20 -i 100  k6LoggingPerfScript.js --out csv=benchmark_outputs/fasttracksqlitelogging.csv -e HOSTNAME=fasttrack:5000 
      working_dir: /src
      volumes:
        - .:/src
      networks:
        - fasttrack_network
      depends_on:
        - fasttrack
      
    logging_test_fasttrack_postgres:
      image: grafana/k6:latest
      command: run  -u 20 -i 100  k6LoggingPerfScript.js --out csv=benchmark_outputs/fasttrackpostgreslogging.csv -e HOSTNAME=fasttrackpostgres:5000 
      working_dir: /src
      volumes:
        - .:/src
      networks:
        - fasttrack_network
      depends_on:
        - fasttrackpostgres

    retrieval_test_mlflow_sqlite:
      image: grafana/k6:latest
      command: run  -u 20 -i 100  k6RetrievalPerfScript.js --out csv=benchmark_outputs/mlflowsqliteretrieval.csv -e HOSTNAME=mlflow:5000 
      working_dir: /src
      volumes:
        - .:/src
      networks:
        - mlflow_network
      depends_on:
        - mlflow

    retrieval_test_mlflow_postgres:
      image: grafana/k6:latest
      command: run -u 20 -i 100 k6RetrievalPerfScript.js --out csv=benchmark_outputs/mlflowpostgresretrieval.csv -e HOSTNAME=mlflowpostgres:5000 
      working_dir: /src
      volumes:
        - .:/src
      networks:
        - mlflow_network
      depends_on:
        - mlflowpostgres
      
    retrieval_test_fasttrack_postgres:
      image: grafana/k6:latest
      command: run  -u 20 -i 100  k6RetrievalPerfScript.js --out csv=benchmark_outputs/fasttrackpostgresretrieval.csv -e HOSTNAME=fasttrackpostgres:5000 
      working_dir: /src
      volumes:
        - .:/src
      networks:
        - fasttrack_network
      depends_on:
        - fasttrackpostgres

    retrieval_test_fasttrack_sqlite:
      image: grafana/k6:latest
      command: run  -u 20 -i 100  k6RetrievalPerfScript.js --out csv=benchmark_outputs/fasttracksqliteretrieval.csv -e HOSTNAME=fasttrack:5000 
      working_dir: /src
      volumes:
        - .:/src
      networks:
        - fasttrack_network
      depends_on:
        - fasttrack

    performance_benchmark_test: 
      build: .
      working_dir: /src
      volumes:
        - .:/src

networks:
  mlflow_network:
  fasttrack_network:
