name: buildwheels

on: workflow_dispatch

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      matrix:
        os: [macos-11]
    steps:
    - uses: actions/checkout@v3
    - name: Configure linux build environment
      if: runner.os == 'Linux'
      run: |
        mkdir -p bin
        mv dist/fasttrackml_linux_arm64/fml bin/fml
        chmod +x bin/fml
    - name: Configure macOS build environment
      if: runner.os == 'macOS'
      run: |
        mkdir -p bin
        mv dist/fasttrackml_macos_arm64/fml bin/fml
        chmod +x bin/fml
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.14.1
      env:
        CIBW_ARCHS_MACOS: arm64, x86_64
        CIBW_ARCHS_LINUX: auto64
        CIBW_SKIP: pp*
        CIBW_BUILD_VERBOSITY: 1
    - name: Build source distribution
      if: runner.os == 'Linux' # Only release source under linux to avoid conflict
      run: |
        python3 -m pip install wheel
        python3 setup.py sdist
        mv dist/*.tar.gz wheelhouse/
  github-release:
    name: Publish GitHub release
    needs: build_wheels
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        run: gh run download ${{ github.event.workflow_run.id }} --repo ${{ github.event.workflow_run.repository.full_name }} --name fasttrackml-archives --dir dist
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: wheelhouse/*
          tag_name: ${{ github.event.workflow_run.head_branch }}
 
