name: CI

on:
  push:
  pull_request:
  schedule:
    # Run daily at 01:34 so we get notified if CI is broken before a pull request
    # is submitted.
    - cron: "34 1 * * *"

permissions:
  contents: read

jobs:
  lint:
    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  golang-unit-tests:
    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    name: Golang Unit Tests
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  # Virtual job that can be configured as a required check before a PR can be merged.
  all-required-checks-done:
    name: All required checks done
    if: ${{ always() }}
    needs:
      - lint
      - golang-unit-tests
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ $(jq 'all(. == "success")' <<EOF
          ${{ toJson(needs.*.result) }}
          EOF
          ) == "true" ]; then
            echo "All required checks succeeded"
          else
            echo ::error ::"Some required checks failed"
          fi
