name: Goreleaser

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  goreleaser:
    name: Goreleaser artifact build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node build
        run:  docker run -v ${{ github.workspace }}:/app -w "/app" node:16 make node-build

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Run GoReleaser to build release artifacts
        uses: goreleaser/goreleaser-action@v4
        with:
          version: v1.19.1
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
