name: Release

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  goreleaser:
    name: Goreleaser artifact build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run goreleaser in docker
        run: |
          docker run \
          --rm \
          -e CGO_ENABLED=1 \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v `pwd`:/go/src/fasttrackml \
          -v `pwd`/sysroot:/sysroot \
          -w /go/src/fasttrackml \
          ghcr.io/goreleaser/goreleaser-cross:v1.19.5 \
          release --snapshot --clean

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/fasttrackml_Darwin_arm64.tar.gz
            ./dist/fasttrackml_Darwin_x86_64.tar.gz
            ./dist/fasttrackml_Linux_arm64.tar.gz
            ./dist/fasttrackml_Linux_x86_64.tar.gz
            ./dist/fasttrackml_Windows_arm64.zip
            ./dist/fasttrackml_Windows_x86_64.zip
