name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  golang-release:
    name: Release Go binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run GoReleaser
        run: make go-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
