name: Release

on:
  workflow_run:
    types: [completed]
    workflows: [CI]
    branches:
      - main
      - v*

jobs:
  release:
    name: Publish container image to DockerHub
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Compute tags
        id: tags
        run: |
          ref=${{ github.event.workflow_run.head_branch }}
          case $ref in
            main)
              tags=("main" "edge")
              ;;
            v*)
              tags=("${ref#v}")
              if [ $(git describe --tags --abbrev=0) == $ref ]; then
                tags+=("latest")
              fi
          esac
          echo "tags=${tags[@]}" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v1.19.1
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
