name: Release

on:
  workflow_call:

permissions:
  contents: read

jobs:
  aws-release:
    needs: docker-release
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull gresearch/fasttrackml
      - name: Delete old container
        run: docker rm -f 
      - name: Run docker container go-app-container
        run: docker run -d -p 80:5000 --name go-app-container gresearch/fasttrackml
    